### ISSUE TITLE
Question on firing a different event per state.

### ISSUE THREAD

**Issue by philpott** [Ayudante/gtm-consent-listener#1]
I see the the trigger will fire a different event per state change. I was wondering what's the advantage or usecase of this vs firing a single event on state change and using the built in consent checks (Advanced Settings -> Consent Settings -> Additional Consent Checks) to minimize the amount of triggers required to fire the tag  -- and be able to leverage bulk editing and the consent overview feature. 

Thanks for any info, we are always looking to improve the product/feature.

**Comment by DaisakuHataoka** [comment]
Hi, philpott.
Thanks for checking.

The case I'm thinking of is
- Tags with no "built-in consent check
- Custom HTML tags

and you want the tag to fire when consent is given (without page transition).

Normally, the timing of user consent on the first page is later than that of page view and so on.
However, a tag that does not include a built-in consent check cannot fire the tag again after the consent status has changed.
This is especially problematic for users who leave the first page without ever firing the tag.

In order to avoid this, we needed to detect when the user's consent status changed.

However, it is a painful process because, as you say, "it increases the number of triggers".
To tell the truth, I think it would be ideal if GTM's default feature would be to refire tags with Additional Consent Checks when the consent status changes.

I hope this is helpful.

**Comment by philpott** [comment]
I'll pass the feedback on for tag refiring to our PM's we've had a few requests for this since the feature has launched.

As far as firing tags again when consent is granted (for those that do not support built-in consent checks) what we are advising is to create a trigger that simply fires when the consent state is updated and use ([tag consent settings > additional consent checks](https://support.google.com/tagmanager/answer/10718549?hl=en) to handle the consent checking logic. This way it's easy to handle both single and multiple consent type checks.

How this would be done:
1. Configure additional consent checks on those tags that do not have built-in consent checking.
2. Add the consent update trigger that looks for the event your template creates when any consent check is done.

When the update is fired the GTM runtime logic would check against the specified consent types to verify what is granted.
This also allows the users to use bulk editing to do more fine grain consent settings/updates and if re-firing is introduced they'll simply need to remove the consent updated trigger and already have their consent logic configured.

**Comment by DaisakuHataoka** [comment]
Thanks, philpott!

> Add the consent update trigger that looks for the event your template creates when any consent check is done.

This template was a "just in case" template in case the consent tool template does not provide "the event your template creates when any consent check".
(So you are correct in pointing out that it should not be needed.)

GTM has always been a great help to me.
Looking forward to better products in the future, big thanks to you all.
